Repository Programmers-HandsUp/FE-HandsUp, pull requests merged in 2024-04, with the labels that each got.

#277 refactor : 공용컴포넌트 - Input 리펙토링
  .gitignore
  src/app/_component/common/Feild/index.tsx
  src/app/_component/common/Input/Input.variants.ts
  src/app/_component/common/Input/InputForm.tsx
  src/app/_component/common/Input/InputInnerBox.tsx
  src/app/_component/common/Input/InputInnerBox.variants.ts
  src/app/_component/common/Input/InputWrapper.variants.ts
  src/app/_component/common/Input/SubmitButton.tsx
  src/app/_component/common/Input/_components/ClearButton.tsx
  src/app/_component/common/Input/_components/ClearButton.variants.ts
  src/app/_component/common/Input/_components/InputForm.tsx
  src/app/_component/common/Input/_components/SubmitButton.tsx
  src/app/_component/common/Input/_components/SubmitButton.variants.ts
  src/app/_component/common/Input/index.tsx
  src/app/search/[searchString]/_component/SearchFilter.tsx
  src/app/search/_component/SearchBar.tsx
  src/app/signin/_component/EmailLoginForm.tsx
  src/app/signup/_component/SignupForm.tsx
Labels: 🔨Refactor

#279 refactor: 상태 기반 조건부 렌더링을 위한 재사용 가능한 컴포넌트 구현
  src/app/(userpage)/_components/PurchaseHistory/index.tsx
  src/app/(userpage)/_components/SalesHistory/Bidding.tsx
  src/app/(userpage)/_components/SalesHistory/Finished.tsx
  src/app/(userpage)/_components/SalesHistory/Pending.tsx
  src/app/(userpage)/_components/SalesHistory/SalesHistory.tsx
  src/app/(userpage)/_components/SalesHistory/StatusComponents.tsx
  src/app/(userpage)/_components/SalesHistory/index.tsx
  src/app/(userpage)/_components/Transaction/TransactionItem.tsx
  src/app/(userpage)/_components/TransactionList/index.tsx
  src/app/(userpage)/_utils/formatDate.ts
  src/utils/types/user/mypage.ts
Labels: 🔨Refactor

#281 feat: 로그아웃 기능 구현
  src/app/(userpage)/_api/mypage.ts
  src/app/(userpage)/_hooks/mutations/useLogout.ts
  src/app/(userpage)/_utils/deleteCookie.ts
  src/app/(userpage)/my/_components/MyInfo/index.tsx
Labels: ✨Feature

#283 fix: 토큰이 쿠키에 존재하지 않을 경우 알림 관련 data fetching이 안되도록 수정
  src/app/_component/common/Navigation/index.tsx
  src/app/_component/notification/_api/notification.ts
  src/app/_component/notification/_component/NotificationList.tsx
  src/app/_component/notification/index.tsx
  src/middleware.ts
Labels: 🐞BugFix
