Repository Programmers-HandsUp/FE-HandsUp, pull requests merged in 2024-02, with the labels that each got.

#5 setting: Tailwind 환경 세팅
  .vscode/settings.json
  package.json
  src/utils/cn.ts
  tailwind.config.ts
  yarn.lock
Labels: ⚙Setting

#9 settings : Yarn-berry 적용
  .gitignore
  .yarn/releases/yarn-4.1.0.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: ⚙Setting

#15 feat: Icon 컴포넌트 구현
  .eslintcache
  .eslintrc.json
  public/assets/icon-sprite.svg
  src/app/_component/common/Icon/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/page.tsx
  tsconfig.json
Labels: ✨Feature, 📢리뷰반영완료

#25 feat: 전체 레이아웃 구현
  src/app/globals.css
  src/app/layout.tsx
Labels: 🎨Html&css

#19 feat: Badge 컴포넌트 구현
  .husky/pre-commit
  src/app/_component/common/Badge/Badge.variants.tsx
  src/app/_component/common/Badge/index.tsx
Labels: ✨Feature, 📢리뷰반영완료

#26 feat: Font 추가
  public/assets/font/YeongdeokSea.ttf
  src/app/globals.css
  tailwind.config.ts
Labels: 🎨Html&css, 🔥빠른승인요청

#33 feat: Header 컴포넌트 구현
  public/assets/icon-sprite.svg
  src/app/_component/common/Header/index.tsx
  src/app/_component/common/Icon/type.ts
Labels: ✨Feature

#28 feat : BookMark 버튼 구현
  src/app/_component/common/Bookmark/ShadowSize.variants.ts
  src/app/_component/common/Bookmark/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#32 feat: Tooltip 컴포넌트 구현
  src/app/_component/common/Tooltip/Tooltip.variants.ts
  src/app/_component/common/Tooltip/index.tsx
  src/app/_component/common/Tooltip/useInteraction.ts
Labels: ✨Feature

#38 feat: ArrowBackButton 구현
  src/app/_component/common/ArrowBackButton/index.tsx
Labels: ✨Feature

#40 Settings : MSW 도입 및 auth 관련, 경매 포스트 관련 Mocking APi 구현
  .vscode/settings.json
  package.json
  public/mockServiceWorker.js
  src/app/_component/common/Input/Input.variants.ts
  src/app/_component/common/Input/index.tsx
  src/app/page.tsx
  src/utils/mockServer/api/auctionPostApis.ts
  src/utils/mockServer/api/authApis.ts
  src/utils/mockServer/api/data/authData.ts
  src/utils/mockServer/api/data/postListData.ts
  src/utils/mockServer/api/types.ts
  src/utils/mockServer/browser.ts
  src/utils/mockServer/handlers.ts
  src/utils/mockServer/index.ts
  src/utils/mockServer/server.ts
  tsconfig.json
Labels: ✨Feature, ⚙Setting

#39 feat: Navigation 구현
  public/assets/icon-sprite.svg
  src/app/_component/common/Icon/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/Navigation/LoginLink.tsx
  src/app/_component/common/Navigation/index.tsx
  src/app/_component/common/Toast/ToastItem.tsx
  src/app/_component/common/Toast/ToastManager.tsx
  src/app/_component/common/Toast/index.tsx
Labels: ✨Feature, 📢리뷰반영완료

#37 feat: ThemeButton 버튼 구현
  public/assets/icon-sprite.svg
  src/app/_component/ThemeScript/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/ThemeButton/index.tsx
  src/app/_component/common/ThemeButton/useDarkMode.ts
  src/app/globals.css
  src/app/layout.tsx
Labels: ✨Feature, 📢리뷰반영완료

#43 feat: geolocation을 이용한 사용자 현재 위치 구현
  src/app/hooks/useGeolocation.ts
Labels: ✨Feature

#42 feat: Button 컴포넌트 구현
  src/app/_component/common/Button/Button.variants.ts
  src/app/_component/common/Button/index.tsx
Labels: ✨Feature, 📢리뷰반영완료

#55 feat: Chips 컴포넌트 구현
  public/assets/icon-sprite.svg
  src/app/_component/common/Chips/Chip.tsx
  src/app/_component/common/Chips/Chip.variants.ts
  src/app/_component/common/Chips/Chips.tsx
  src/app/_component/common/Chips/Chips.variants.ts
  src/app/_component/common/Chips/index.tsx
  src/app/_component/common/Navigation/LoginLink.tsx
Labels: ✨Feature

#58 feat : 유저 카드 컴포넌트 구현
  public/logoIcon.png
  src/app/_component/common/UserCard/UserCardContentArea.tsx
  src/app/_component/common/UserCard/index.tsx
  src/app/page.tsx
Labels: ✨Feature

#63 fix: cookie로 다크모드 설정
  src/app/_component/ThemeScript/index.tsx
  src/app/_component/common/ThemeButton/useDarkMode.ts
  src/app/layout.tsx
  src/utils/cookie.ts
Labels: 🐞BugFix, 📢리뷰반영완료, 🔥빠른승인요청

#60 feat: 채팅 메세지 컴포넌트 구현
  src/app/_component/common/ChatMessage/Chatmessage.variants.ts
  src/app/_component/common/ChatMessage/index.tsx
Labels: ✨Feature

#61 feat : Input 컴포넌트 구현
  src/app/_component/common/Input/Input.variants.ts
  src/app/_component/common/Input/InputForm.tsx
  src/app/_component/common/Input/InputInnerBox.tsx
  src/app/_component/common/Input/InputInnerBox.variants.ts
  src/app/_component/common/Input/SubmitButton.tsx
  src/app/_component/common/Input/SubmitButton.variants.ts
  src/app/_component/common/Input/index.tsx
  src/app/hello.tsx
  src/app/page.tsx
Labels: ✨Feature

#21 feat : Carousel 컴포넌트 구현
  .env
  src/app/_component/common/Carousel/Carousel.variants.ts
  src/app/_component/common/Carousel/Indicator.tsx
  src/app/_component/common/Carousel/MoveButtonsUI.tsx
  src/app/_component/common/Carousel/index.tsx
  src/app/page.tsx
  src/public/tempImage.png
  src/public/tempLeftButton.svg
Labels: ✨Feature, 📢리뷰반영완료

#66 feat : MSW - 토큰 발급 api, 유저정보 조회 api 구현 및 관리자 계정, 모킹 데이터 추가
  package.json
  src/utils/mockServer/api/authApis.ts
  src/utils/mockServer/api/data/authData.ts
  src/utils/mockServer/api/data/token.ts
  src/utils/mockServer/api/data/userData.ts
  src/utils/mockServer/api/types.ts
  yarn.lock
Labels: ✨Feature

#52 feat: 매너 온도 컴포넌트 구현
  src/app/_component/common/Reliabilitybar/Reliability.variants.ts
  src/app/_component/common/Reliabilitybar/index.tsx
  src/app/globals.css
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#54 feat: 주소 검색 기능 구현
  package.json
  src/app/_component/common/searchAddress/_component/AddrList.tsx
  src/app/_component/common/searchAddress/_component/EmptyResults.tsx
  src/app/_component/common/searchAddress/index.tsx
  src/app/api/address.ts
  src/app/globals.css
  src/app/hooks/queries/useSearchAddrQuery.ts
  src/app/layout.tsx
  src/app/types/address.ts
  src/utils/provider.tsx
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#57 feat: 가격 입력 컴포넌트 구현
  .prettierrc
  package.json
  src/app/_component/common/InputPrice/_component/PriceButton.tsx
  src/app/_component/common/InputPrice/index.tsx
  src/app/_component/common/InputPrice/utils/formatPrice.ts
  src/app/_component/common/InputPrice/utils/validation.ts
Labels: ✨Feature, 📢리뷰반영완료

#71 feat: MSW 컴포넌트 구현 및 서버 통신 기능 구현
  package.json
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/utils/MSWComponent.tsx
  src/utils/mockServer/index.ts
  src/utils/mockServer/server.ts
  src/utils/mocks/api/auctionPostApis.ts
  src/utils/mocks/api/authApis.ts
  src/utils/mocks/api/data/authData.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/data/token.ts
  src/utils/mocks/api/data/userData.ts
  src/utils/mocks/api/types.ts
  src/utils/mocks/browser.ts
  src/utils/mocks/handlers.ts
  src/utils/mocks/http.ts
  yarn.lock
Labels: ✨Feature

#76 feat: useModal 구현
  src/app/globals.css
  src/app/hooks/useClickAway.ts
  src/app/hooks/useModal/ModalType.variants.ts
  src/app/hooks/useModal/index.tsx
  src/app/layout.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: ✨Feature

#92 refactor: className 커스텀 기능 추가
  src/app/hooks/useModal/index.tsx
  src/app/hooks/useModal/type.ts
Labels: 🔨Refactor, 🔥빠른승인요청

#90 feat: debounce hook 구현
  src/app/hooks/useDebounce.ts
Labels: ✨Feature, 🔥빠른승인요청

#81 refactor: className 커스텀 가능 및 selectedStyle 커스텀 기능 추가
  public/assets/images/bad.webp
  public/assets/images/good.webp
  public/assets/images/normal.webp
  public/assets/images/soso.webp
  public/assets/images/veryGood.webp
  src/app/_component/common/Chips/Chip.tsx
  src/app/_component/common/Chips/Chip.variants.ts
  src/app/_component/common/Chips/Chips.tsx
Labels: 🔨Refactor

#84 feat: 상품 등록 페이지 구현
  package.json
  public/assets/icon-sprite.svg
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/InputPrice/PriceButton.tsx
  src/app/_component/common/InputPrice/formatPrice.ts
  src/app/_component/common/InputPrice/index.tsx
  src/app/_component/common/InputPrice/utils/validation.ts
  src/app/_component/common/searchAddress/AddrList.tsx
  src/app/_component/common/searchAddress/EmptyResults.tsx
  src/app/_component/common/searchAddress/SearchAddress.tsx
  src/app/_component/common/searchAddress/_component/EmptyResults.tsx
  src/app/_component/common/searchAddress/index.tsx
  src/app/products/new/_components/AuctionInfo/index.tsx
  src/app/products/new/_components/InputLabel/index.tsx
  src/app/products/new/_components/ProductInfo/CategoryList/index.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImagePreviewer.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImageUploader.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/index.tsx
  src/app/products/new/_components/ProductInfo/index.tsx
  src/app/products/new/_components/SearchAddressBtn/index.tsx
  src/app/products/new/page.tsx
  tailwind.config.ts
Labels: ✨Feature

#88 feat : 공통 컴포넌트 프로그레스바 구현
  .gitignore
  src/app/_component/common/ProgressBar/ProgressBar.variants.ts
  src/app/_component/common/ProgressBar/index.tsx
  src/app/page.tsx
Labels: ✨Feature

#97 refactor: ProductCard 컴포넌트에 합성 컴포넌트 패턴 적용 및 수정
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/_component/common/ProductCard/ProductCard.variants.tsx
  src/app/_component/common/ProductCard/ProductState.variatns.tsx
  src/app/_component/common/ProductCard/index.tsx
  yarn.lock
Labels: 🔨Refactor
