Repository Programmers-HandsUp/FE-HandsUp, pull requests merged in 2024-03, with the labels that each got.

#86 feat: html2canvas를 이용한 후기 작성 완료 페이지 이미지 저장 기능 구현
  package.json
  public/assets/barcode.webp
  public/assets/icon-sprite.svg
  public/assets/logo.webp
  src/app/globals.css
  src/app/review/complete/page.tsx
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#108 refactor: Provider 환경 세팅 수정
  src/utils/provider.tsx
Labels: 🔨Refactor, 🔥빠른승인요청

#95 fix: 상품 등록 컴포넌트 수정
  package.json
  src/app/_component/common/InputPrice/formatPrice.ts
  src/app/_component/common/InputPrice/index.tsx
  src/app/_component/common/searchAddress/SearchAddress.tsx
  src/app/products/new/_components/AuctionInfo/index.tsx
  src/app/products/new/_components/InputLabel/index.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImagePreviewer.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImageUploader.tsx
  src/app/products/new/_components/ProductInfo/index.tsx
  src/app/products/new/_components/SearchAddressBtn/index.tsx
  src/app/products/new/page.tsx
Labels: 🐞BugFix, 📢리뷰반영완료

#109 feat: 경매 상세 페이지의 차트 구현
  package.json
  public/assets/images/transparentMan.png
  public/assets/images/whiteMan.png
  src/app/_component/common/LineChart/index.tsx
  src/app/_component/common/TopThreeRank/index.tsx
  src/app/api/bids.ts
  src/app/globals.css
  src/app/hooks/queries/useBidsQuery.ts
  src/utils/mocks/api/bids.ts
  src/utils/mocks/api/data/bidData.ts
  src/utils/mocks/api/types.ts
  src/utils/mocks/handlers.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨Feature

#98 feat: 메인페이지 구현
  public/assets/icon-sprite.svg
  public/mockServiceWorker.js
  src/app/(navigation)/home/_component/AuctionFeedList/AuctionFeedList.variants.ts
  src/app/(navigation)/home/_component/AuctionFeedList/DefaultCard.tsx
  src/app/(navigation)/home/_component/AuctionFeedList/index.tsx
  src/app/(navigation)/home/_component/DetailAuctionFeed/index.tsx
  src/app/(navigation)/home/_component/RegionSelect/index.tsx
  src/app/(navigation)/home/layout.tsx
  src/app/(navigation)/home/page.tsx
  src/app/(navigation)/layout.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/_component/common/ProductCard/ProductCard.variants.tsx
  src/app/_component/common/SlideCarousel/index.tsx
  src/app/_component/common/SlideCarousel/useDragScroll.ts
  src/app/_component/common/ThemeButton/useDarkMode.ts
  src/app/_component/common/Timer/index.tsx
  src/app/api/auctionRecommends.ts
  src/app/globals.css
  src/app/layout.tsx
  src/utils/arrayDivider.ts
  src/utils/mocks/api/auctionPostApis.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/types.ts
Labels: ✨Feature, 📢리뷰반영완료, 🔥빠른승인요청

#105 feat: 마이페이지 구현
  src/app/_component/common/Avatar/Avatar.variants.ts
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/api/mypage.ts
  src/app/hooks/queries/usePurchaseList.ts
  src/app/hooks/queries/usePurchaseStatusList.ts
  src/app/hooks/queries/useReviewLabelList.ts
  src/app/hooks/queries/useReviewList.ts
  src/app/hooks/queries/useSaleList.ts
  src/app/hooks/queries/useSaleStatusList.ts
  src/app/my/[slug]/page.tsx
  src/app/my/_components/AllReviews/index.tsx
  src/app/my/_components/BoxLayout/index.tsx
  src/app/my/_components/Profile/index.tsx
  src/app/my/_components/ReviewItem/index.tsx
  src/app/my/_components/TransactionList/SelectStatusTab.tsx
  src/app/my/_components/TransactionList/TransactionItem.tsx
  src/app/my/_components/TransactionList/TransactionListHeader.tsx
  src/app/my/_components/TransactionList/index.tsx
  src/app/my/_components/TransactionStatus/StatusCard.tsx
  src/app/my/_components/TransactionStatus/index.tsx
  src/app/my/page.tsx
  src/app/my/types.ts
  src/utils/mocks/api/data/mypageData.ts
  src/utils/mocks/api/mypageApis.ts
  src/utils/mocks/handlers.ts
Labels: ✨Feature, 📢리뷰반영완료

#113 feat: 거래 후기 페이지 구현
  src/app/review/SelectRange.tsx
  src/app/review/SelectReview.tsx
  src/app/review/page.tsx
Labels: ✨Feature

#114 feat: 구매 페이지 구현
  src/app/purchase/AuctionBanner.tsx
  src/app/purchase/AuctionRanking.tsx
  src/app/purchase/OfferPrice.tsx
  src/app/purchase/page.tsx
Labels: ✨Feature

#102 feat : 로그인 페이지 구현
  .gitignore
  public/assets/google-icon.png
  public/assets/logoIcon.png
  public/assets/naver-icon.png
  public/assets/whiteNaverIcon.svg
  src/app/_component/common/Input/InputForm.tsx
  src/app/api/auth.ts
  src/app/hooks/queries/useAuth.ts
  src/app/login/component/EmailLoginForm.tsx
  src/app/login/component/SocialLoginContainer.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/utils/mocks/api/authApis.ts
  tsconfig.json
Labels: ✨Feature, 📢리뷰반영완료

#101 feat : 온보딩 페이지 구현
  .env
  .gitignore
  next.config.njs
  src/app/_component/common/Button/index.tsx
  src/app/_component/common/Chips/Chip.tsx
  src/app/_component/common/Chips/Chips.tsx
  src/app/_component/common/Input/InputForm.tsx
  src/app/_component/common/ProgressBar/index.tsx
  src/app/globals.css
  src/app/hooks/useFunnel.ts
  src/app/onboarding/component/SignupHeader.tsx
  src/app/onboarding/component/funnel/FinishFunnel.tsx
  src/app/onboarding/component/funnel/SelectCategory.tsx
  src/app/onboarding/component/funnel/SelectResidence.tsx
  src/app/onboarding/component/funnel/UserProfileSetting.tsx
  src/app/onboarding/component/store/store.ts
  src/app/onboarding/page.tsx
  src/utils/onGetImageFile.tsx
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#127 feat: BidsSection 컴포넌트 구현 및 fire 컴포넌트 구현
  src/app/_component/common/AuctionBidsSection/index.tsx
  src/app/_component/common/FireAnimation/index.tsx
  src/app/globals.css
Labels: ✨Feature

#115 feat: 상품 등록 API 연동
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/InputPrice/index.tsx
  src/app/_component/common/searchAddress/SearchAddress.tsx
  src/app/api/registerProduct.ts
  src/app/hooks/mutations/useImageUpload.ts
  src/app/hooks/mutations/useReigsterProduct.ts
  src/app/hooks/queries/useSearchAddrQuery.ts
  src/app/products/new/_components/AuctionInfo/index.tsx
  src/app/products/new/_components/InputLabel/index.tsx
  src/app/products/new/_components/ProductInfo/CategoryList/index.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImagePreviewer.tsx
  src/app/products/new/_components/ProductInfo/ImageUploader/ImageUploader.tsx
  src/app/products/new/_components/ProductInfo/index.tsx
  src/app/products/new/_components/SearchAddressBtn/index.tsx
  src/app/products/new/_utils/constants.ts
  src/app/products/new/_utils/productType.ts
  src/app/products/new/_utils/useBeforeUnload.ts
  src/app/products/new/_utils/validation.ts
  src/app/products/new/page.tsx
  src/utils/mocks/handlers.ts
Labels: ✨Feature

#103 feat : 회원 가입 페이지 기능 구현
  .gitignore
  src/app/_component/common/Input/InputForm.tsx
  src/app/api/auth.ts
  src/app/globals.css
  src/app/hooks/mutations/useIdDuplicateCheck.ts
  src/app/hooks/mutations/useSignin.ts
  src/app/hooks/mutations/useSignup.ts
  src/app/login/component/EmailLoginForm.tsx
  src/app/login/component/SocialLoginContainer.tsx
  src/app/page.tsx
  src/app/signup/SignupForm.tsx
  src/app/signup/page.tsx
  src/app/types/loginForm.ts
  src/utils/mocks/api/authApis.ts
  tailwind.config.ts
Labels: ✨Feature, 📢리뷰반영완료

#122 feat : 검색페이지 기능 구현
  public/assets/icon-sprite.svg
  public/assets/likeIcon.svg
  src/app/_component/common/DropDown/index.tsx
  src/app/_component/common/Icon/index.tsx
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/_component/common/ProductCard/index.tsx
  src/app/api/ popularKeyword.ts
  src/app/api/getSearchResults.tsx
  src/app/hooks/queries/useGetPopluarKeyword.ts
  src/app/hooks/queries/useGetSearchResults.ts
  src/app/hooks/useInfiniteScroll.ts
  src/app/search/[slug]/component/SearchFilter.tsx
  src/app/search/[slug]/page.tsx
  src/app/search/component/RealTimePopluar.tsx
  src/app/search/component/RecentSearch.tsx
  src/app/search/component/SearchBar.tsx
  src/app/search/page.tsx
  src/app/search/utils/setSearchRecordInLocalStorage.ts
  src/utils/mocks/api/data/popularSearchData.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/searchApis.ts
  src/utils/mocks/handlers.ts
Labels: ✨Feature, 📢리뷰반영완료

#126 feat: AuctionDetailFooterBar 컴포넌트 구현 및 타입 추가
  src/app/_component/common/AuctionDetailFooterBar/index.tsx
  src/app/types/product.ts
Labels: ✨Feature, 📢리뷰반영완료

#131 refactor: useModal 성능 최적화 및 버그 수정
  src/app/(navigation)/home/_component/RegionSelect/index.tsx
  src/app/_component/common/Chips/Chip.tsx
  src/app/_component/common/Chips/Chips.tsx
  src/app/_component/common/Modal/ModalType.variants.ts
  src/app/_component/common/Modal/index.tsx
  src/app/globals.css
  src/app/hooks/useModal/index.tsx
  src/app/hooks/useModal/type.ts
  src/app/hooks/useModalState/index.tsx
  src/app/products/new/_components/SearchAddressBtn/index.tsx
Labels: 🐞BugFix, 🔨Refactor, 🔥빠른승인요청

#116 feat: Comment 컴포넌트 구현
  src/app/_component/common/ChatMessage/Chatmessage.variants.ts
  src/app/_component/common/ChatMessage/index.tsx
  src/app/_component/common/Comment/CommentInput.tsx
  src/app/_component/common/Comment/index.tsx
  src/app/_component/common/Comment/useGetCommentList.ts
  src/app/api/createComment.ts
  src/app/api/getComments.ts
  src/app/globals.css
  src/app/hooks/useInfiniteScroll.ts
  src/utils/mocks/api/auctionPostApis.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/types.ts
  yarn.lock
Labels: ✨Feature, 📢리뷰반영완료

#129 refactor: 거래 내역 컴포넌트 합성 컴포넌트 패턴으로 수정
  src/app/api/mypage.ts
  src/app/my/_components/BoxLayout/index.tsx
  src/app/my/_components/PurchaseHistory/index.tsx
  src/app/my/_components/SalesHistory/Bidding.tsx
  src/app/my/_components/SalesHistory/Finished.tsx
  src/app/my/_components/SalesHistory/Pending.tsx
  src/app/my/_components/SalesHistory/SalesHistory.tsx
  src/app/my/_components/SalesHistory/index.tsx
  src/app/my/_components/Tab/Tab.variants.ts
  src/app/my/_components/Tab/index.tsx
  src/app/my/_components/Transaction/Transaction.tsx
  src/app/my/_components/Transaction/TransactionItem.tsx
  src/app/my/_components/TransactionList/SelectStatusTab.tsx
  src/app/my/_components/TransactionList/TransactionItem.tsx
  src/app/my/_components/TransactionList/TransactionListHeader.tsx
  src/app/my/_components/TransactionList/index.tsx
  src/app/my/_components/TransactionStatus/StatusCard.tsx
  src/app/my/_components/TransactionStatus/index.tsx
  src/app/my/page.tsx
Labels: 🔨Refactor

#136 feat: 경매 상세페이지 구현
  next.config.mjs
  public/assets/icon-sprite.svg
  src/app/(navigation)/home/_component/AuctionFeedList/index.tsx
  src/app/(navigation)/home/_component/DetailAuctionFeed/index.tsx
  src/app/(navigation)/home/page.tsx
  src/app/_component/common/AuctionDetailFooterBar/index.tsx
  src/app/_component/common/AuctionDetailInfo/DefaultCase.tsx
  src/app/_component/common/Avatar/index.tsx
  src/app/_component/common/Comment/index.tsx
  src/app/_component/common/Header/index.tsx
  src/app/_component/common/LineChart/index.tsx
  src/app/_component/common/SlideCarousel/useDragScroll.ts
  src/app/_component/common/TopThreeRank/index.tsx
  src/app/api/getAuctionDetail.ts
  src/app/api/getAuctionRecommends.ts
  src/app/api/getBids.ts
  src/app/api/getComments.ts
  src/app/hooks/queries/useBidsQuery.ts
  src/app/hooks/queries/useGetAuctionDetail.ts
  src/app/hooks/queries/useGetCommentList.ts
  src/app/hooks/queries/useGetPopluarKeyword.ts
  src/app/hooks/useModalState.ts
  src/app/products/[auctionId]/_component/DetailInfoSection.tsx
  src/app/products/[auctionId]/layout.tsx
  src/app/products/[auctionId]/page.tsx
  src/app/search/[slug]/page.tsx
  src/app/types/product.ts
  src/utils/mocks/api/auctionPostApis.ts
  src/utils/mocks/api/data/bidData.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/types.ts
  src/utils/mocks/handlers.ts
Labels: ✨Feature, 🔥빠른승인요청

#154 feat: 사용자 알림 허용 컴포넌트 구현
  public/assets/icon-sprite.svg
  public/firebase-messaging-sw.js
  src/app/_component/common/Icon/type.ts
  src/app/_component/notification/CheckPermission.tsx
  src/app/_component/notification/_component/PermissionDenied.tsx
  src/app/_component/notification/_hooks/useCheckPermission.ts
  src/app/_component/notification/_hooks/useFcmToken.ts
  src/app/_component/notification/_utils/useCheckPermission.ts
Labels: ✨Feature

#161 feat: 스켈레톤 컴포넌트 구현
  src/app/_component/common/Skeleton/ParagraphSkeleton.tsx
  src/app/_component/common/Skeleton/ParagraphSkeleton.variants.ts
  src/app/_component/common/Skeleton/Skeleton.variants.ts
  src/app/_component/common/Skeleton/index.tsx
Labels: ✨Feature

#159 feat: 알림 목록 레이아웃 구현
  public/assets/icon-sprite.svg
  src/app/_component/common/Badge/Badge.variants.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/notification/_component/AuctionNotification.tsx
  src/app/_component/notification/_component/NotificationItem.tsx
  src/app/_component/notification/_component/PersonalNotification.tsx
  src/utils/mocks/api/data/notificationData.ts
  src/utils/mocks/api/notificationApis.ts
  src/utils/mocks/handlers.ts
  src/utils/types/notification/index.ts
Labels: ✨Feature

#156 feat: 메인페이지 헤더에 알림 페이지 링크 추가 및 authCheck 함수 구현
  public/mockServiceWorker.js
  src/app/(navigation)/home/_api/getAuctionRecommends.ts
  src/app/(navigation)/home/_component/AuctionFeedList/index.tsx
  src/app/(navigation)/home/_component/DetailAuctionFeed/index.tsx
  src/app/(navigation)/home/_component/MainContentSection/index.tsx
  src/app/(navigation)/home/_hooks/queries/useRecommendAuction.ts
  src/app/(navigation)/home/error.tsx
  src/app/(navigation)/home/layout.tsx
  src/app/(navigation)/home/page.tsx
  src/app/_component/common/Navigation/index.tsx
  src/app/_hooks/useVisibilityScroll.ts
  src/utils/function/authCheck.ts
  src/utils/function/cookie.ts
  src/utils/function/throttle.ts
  yarn.lock
Labels: ✨Feature, 🐞BugFix

#163 refactor : 로그인, 회원가입, 검색 페이지 실 APi 적용 및 UX개선
  src/app/_component/common/DropDown/index.tsx
  src/app/onboarding/_component/funnel/FinishFunnel.tsx
  src/app/onboarding/_component/funnel/SelectResidence.tsx
  src/app/onboarding/page.tsx
  src/app/search/[searchString]/_component/NotResult.tsx
  src/app/search/[searchString]/_component/SearchFilter.tsx
  src/app/search/[searchString]/_component/SearchHeader.tsx
  src/app/search/[searchString]/error.tsx
  src/app/search/[searchString]/layout.tsx
  src/app/search/[searchString]/loading.tsx
  src/app/search/[searchString]/page.tsx
  src/app/search/[slug]/page.tsx
  src/app/search/_api/getPopularKeyword.ts
  src/app/search/_api/getSearchResults.tsx
  src/app/search/_component/RealTimePopluar.tsx
  src/app/search/_component/RealTimePopular.tsx
  src/app/search/_hooks/queries/useGetSearchResults.ts
  src/app/search/_utils/setSearchRecordInLocalStorage.ts
  src/app/search/error.tsx
  src/app/search/layout.tsx
  src/app/search/loading.tsx
  src/app/search/page.tsx
  src/app/signin/_api/login.ts
  src/app/signup/_api/idDuplicateCheck.ts
  src/app/signup/_api/signUp.ts
  src/app/signup/_component/SignupForm.tsx
  src/utils/types/search/search.ts
  tsconfig.json
Labels: ✨Feature

#167 fix: 북마크 아이콘 수정
  public/assets/icon-sprite.svg
  src/app/_component/common/Bookmark/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/Navigation/index.tsx
  src/app/_component/notification/_component/PersonalNotification.tsx
  src/app/search/[searchString]/page.tsx
Labels: 🐞BugFix

#169 feat : 신고페이지 구현
  src/app/_component/common/Reliabilitybar/index.tsx
  src/app/report/_component/CompleteReport.tsx
  src/app/report/page.tsx
Labels: ✨Feature

#171 Design/#168/image files
  public/assets/icons/favicon.ico
  public/assets/images/bad.webp
  public/assets/images/good.webp
  public/assets/images/logo.webp
  public/assets/images/normal.webp
  public/assets/images/soso.webp
  public/assets/images/textLogo.webp
  public/assets/images/veryGood.webp
  src/app/favicon.ico
  src/app/layout.tsx
Labels: 🎨Html&css

#177 fix: 테마 기본 값 버그 해결 및 북마크 로그인 문제 처리
  src/app/(navigation)/chatrooms/_api/getChatRooms.ts
  src/app/_api/bookmark.ts
  src/app/_component/common/Bookmark/index.tsx
  src/app/_component/common/ThemeButton/useDarkMode.ts
  src/app/_hooks/mutations/useBookmark.ts
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
  src/app/auctions/[auctionId]/_hooks/queries/useGetAuctionDetail.ts
  src/app/auctions/[auctionId]/_hooks/queries/useGetCheckBookmark.ts
  src/app/auctions/[auctionId]/page.tsx
  src/app/auctions/[auctionId]/purchase/_hooks/useBidPost.ts
  src/app/auctions/[auctionId]/review/_api/createReview.ts
Labels: 🐞BugFix

#178 feat: 입찰자 목록 페이지 구현
  public/mockServiceWorker.js
  src/app/_component/common/AuctionDetailFooterBar/index.tsx
  src/app/_component/common/Comment/index.tsx
  src/app/_component/common/LineChart/index.tsx
  src/app/_component/common/SlideCarousel/useDragScroll.ts
  src/app/_component/common/TopThreeRank/index.tsx
  src/app/auctions/[auctionId]/_api/getBids.ts
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
  src/app/auctions/[auctionId]/_hooks/queries/useGetAuctionDetail.ts
  src/app/auctions/[auctionId]/_hooks/queries/useGetCommentList.ts
  src/app/auctions/[auctionId]/bidderList/_api/createChatRoom.ts
  src/app/auctions/[auctionId]/bidderList/_api/getChatRoomInfo.ts
  src/app/auctions/[auctionId]/bidderList/_api/patchCancelBidder.ts
  src/app/auctions/[auctionId]/bidderList/_api/patchCompleteTransaction.ts
  src/app/auctions/[auctionId]/bidderList/_component/BidderStatusItem/index.tsx
  src/app/auctions/[auctionId]/bidderList/_hooks/useCreateChatRoom.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/useGetBids.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/useGetChatRoomInfo.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/usePatchTransactionComplete.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/usePatchTranscationCancel.ts
  src/app/auctions/[auctionId]/bidderList/layout.tsx
  src/app/auctions/[auctionId]/bidderList/page.tsx
  src/app/auctions/[auctionId]/page.tsx
  src/utils/function/cookie.ts
  src/utils/mocks/api/searchApis.ts
  src/utils/types/bid/bids.ts
  src/utils/types/chat/checkChatRoomInfrom.ts
  yarn.lock
Labels: ✨Feature

#180 feat: 낙찰 완료 페이지 구현
  package.json
  src/app/(navigation)/home/_component/MainContentSection/index.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailLoading.tsx
  src/app/auctions/[auctionId]/loading.tsx
  src/app/auctions/[auctionId]/page.tsx
  src/app/auctions/[auctionId]/successful-bid/Loading.tsx
  src/app/auctions/[auctionId]/successful-bid/_component/DefaultComponent.tsx
  src/app/auctions/[auctionId]/successful-bid/_hooks/useGetBidsList.ts
  src/app/auctions/[auctionId]/successful-bid/_hooks/useGetSuccessfulData.ts
  src/app/auctions/[auctionId]/successful-bid/layout.tsx
  src/app/auctions/[auctionId]/successful-bid/page.tsx
  src/utils/LottieFiles/party.json
  yarn.lock
Labels: ✨Feature

#179 feat: 알림 컴포넌트 API 연동
  src/app/_component/common/Skeleton/ParagraphSkeleton.tsx
  src/app/_component/common/Skeleton/ParagraphSkeleton.variants.ts
  src/app/_component/notification/CheckPermission.tsx
  src/app/_component/notification/_api/notification.ts
  src/app/_component/notification/_component/AuctionNotification.tsx
  src/app/_component/notification/_component/EmptyNotification.tsx
  src/app/_component/notification/_component/LoadingSkeleton.tsx
  src/app/_component/notification/_component/NotificationItem.tsx
  src/app/_component/notification/_component/NotificationList.tsx
  src/app/_component/notification/_component/PermissionDenied.tsx
  src/app/_component/notification/_component/PermissionMessage.tsx
  src/app/_component/notification/_component/PersonalNotification.tsx
  src/app/_component/notification/_hooks/mutations/useSendFcmToken.ts
  src/app/_component/notification/_hooks/queries/useNotificationBadge.ts
  src/app/_component/notification/_hooks/queries/useNotificationList.ts
  src/app/_component/notification/_hooks/useFcmToken.ts
  src/app/_component/notification/index.tsx
  src/app/_component/notification/page.tsx
  src/utils/types/notification/index.ts
Labels: ✨Feature

#183 feat: useSession
  src/app/(navigation)/chatrooms/_hooks/useGetChatRooms.ts
  src/app/_api/user.ts
  src/app/_hooks/queries/useSession.ts
  src/app/auctions/[auctionId]/_hooks/queries/useGetAuctionDetail.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/useGetBids.ts
  src/app/my/_hooks/queries/usePurchaseList.ts
  src/app/my/_hooks/queries/usePurchaseStatusList.ts
  src/app/my/_hooks/queries/useReviewLabelList.ts
  src/app/my/_hooks/queries/useReviewList.ts
  src/app/my/_hooks/queries/useSaleList.ts
  src/app/my/_hooks/queries/useSaleStatusList.ts
  src/utils/provider.tsx
  src/utils/types/user/users.ts
Labels: ✨Feature

#165 feat: WebSocket & Stomp 설정
  package.json
  src/app/chat/_hooks/useSendMessage.ts
  src/app/chat/_hooks/useWebSocketConnection.ts
  yarn.lock
Labels: ✨Feature

#192 Design/#191/fix image
  public/assets/icons/favicon.ico
  public/assets/images/angel.webp
  public/assets/images/devil.webp
  public/assets/images/hans.webp
  public/assets/images/textLogo.webp
Labels: 🎨Html&css

#186 feat: 채팅방 페이지 구현 및 채팅 데이터 API 연동
  public/assets/icon-sprite.svg
  src/app/(navigation)/chatrooms/_hooks/useGetChatRooms.ts
  src/app/(navigation)/chatrooms/layout.tsx
  src/app/(navigation)/home/_api/getAuctionRecommends.ts
  src/app/(navigation)/home/_component/MainContentSection/index.tsx
  src/app/(navigation)/layout.tsx
  src/app/_component/common/Navigation/index.tsx
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/_component/common/ProductCard/ProductCard.variants.tsx
  src/app/auctions/[auctionId]/_api/getAuctionDetail.ts
  src/app/auctions/[auctionId]/_api/getBids.ts
  src/app/chatrooms/[chatRoomId]/_api/getChatContent.ts
  src/app/chatrooms/[chatRoomId]/_api/getchatRoomInfo.ts
  src/app/chatrooms/[chatRoomId]/_component/ChatMessageInput.tsx
  src/app/chatrooms/[chatRoomId]/_component/ChatRoomContent.tsx
  src/app/chatrooms/[chatRoomId]/_component/ChatRoomInfoHeader.tsx
  src/app/chatrooms/[chatRoomId]/_hooks/useGetChatData.ts
  src/app/chatrooms/[chatRoomId]/layout.tsx
  src/app/chatrooms/[chatRoomId]/page.tsx
  src/app/chatrooms/_api/getChatRooms.ts
  src/app/chatrooms/_component/ChatRoomList.tsx
  src/app/chatrooms/_hooks/useGetChatRooms.ts
  src/app/chatrooms/error.tsx
  src/app/chatrooms/layout.tsx
  src/app/chatrooms/page.tsx
  src/app/globals.css
  src/utils/types/chat/chatRooms.ts
  src/utils/types/chat/checkChatRoomInfrom.ts
Labels: ✨Feature

#194 feat: 마이페이지 useSuspenseQueries 적용 및 API 연동
  src/app/_component/common/Loading/index.tsx
  src/app/_hooks/queries/useSession.ts
  src/app/auctions/[auctionId]/review/complete/page.tsx
  src/app/my/[slug]/page.tsx
  src/app/my/_api/mypage.ts
  src/app/my/_components/AllReviews/index.tsx
  src/app/my/_components/Layout/index.tsx
  src/app/my/_components/Profile/index.tsx
  src/app/my/_components/ProfileEdit/index.tsx
  src/app/my/_components/ReviewItem/index.tsx
  src/app/my/_components/Transaction/Transaction.tsx
  src/app/my/_components/TransactionList/index.tsx
  src/app/my/_components/UserInfo/index.tsx
  src/app/my/_hooks/queries/usePurchaseList.ts
  src/app/my/_hooks/queries/useReviewLabelList.ts
  src/app/my/_hooks/queries/useSaleList.ts
  src/app/my/_hooks/queries/useUserInfo.ts
  src/app/my/page.tsx
  src/utils/mocks/api/data/mypageData.ts
  src/utils/mocks/api/mypageApis.ts
Labels: ✨Feature

#196 design: 프로젝트 로고 수정
  public/assets/icons/icon-128x128.png
  public/assets/icons/icon-152x152.png
  public/assets/icons/icon-180x180.png
  public/assets/icons/icon-192x192.png
  public/assets/icons/icon-512x512.png
  public/assets/images/hans.webp
  src/app/_component/common/Reliabilitybar/index.tsx
  src/app/_component/common/ThemeButton/useDarkMode.ts
  src/app/layout.tsx
Labels: 🎨Html&css

#198 refactor: useSession 적용 및 메인페이지 리팩토링
  src/app/(navigation)/home/_api/getAuctionRecommends.ts
  src/app/(navigation)/home/_component/AuctionFeedList/DefaultCard.tsx
  src/app/(navigation)/home/_component/MainContentSection/AuctionListSection.tsx
  src/app/(navigation)/home/_component/MainContentSection/MainSectionLoading.tsx
  src/app/(navigation)/home/_component/MainContentSection/index.tsx
  src/app/(navigation)/home/_component/RegionSelect/index.tsx
  src/app/(navigation)/home/_hooks/queries/useRecommendAuction.ts
  src/app/(navigation)/home/layout.tsx
  src/app/(navigation)/home/page.tsx
  src/app/(navigation)/layout.tsx
  src/app/_api/bookmark.ts
  src/app/_component/common/AuctionBidsSection/index.tsx
  src/app/_component/common/Navigation/LoginLink.tsx
  src/app/_component/common/Navigation/index.tsx
  src/app/_component/common/ProductCard/DefaultComponent.tsx
  src/app/_hooks/queries/useSession.ts
  src/app/auctions/[auctionId]/review/_api/createReview.ts
  src/app/auctions/[auctionId]/review/_component/SelectRange.tsx
  src/app/auctions/[auctionId]/review/_component/SelectReview.tsx
  src/app/auctions/[auctionId]/review/page.tsx
  src/utils/function/authCheck.ts
  src/utils/types/auction/auctionReivewEnroll.ts
  src/utils/types/auction/registerAuction.ts
Labels: 🔨Refactor

#204 feat: 사용자 프로필 조회 API 이용해서 마이페이지와 유저페이지 구분하여 구현
  src/app/(userpage)/_api/mypage.ts
  src/app/(userpage)/_components/AllReviews/index.tsx
  src/app/(userpage)/_components/BoxLayout/index.tsx
  src/app/(userpage)/_components/Info/index.tsx
  src/app/(userpage)/_components/Profile/index.tsx
  src/app/(userpage)/_components/ProfileEdit/index.tsx
  src/app/(userpage)/_components/PurchaseHistory/index.tsx
  src/app/(userpage)/_components/ReviewItem/index.tsx
  src/app/(userpage)/_components/SalesHistory/Bidding.tsx
  src/app/(userpage)/_components/SalesHistory/Finished.tsx
  src/app/(userpage)/_components/SalesHistory/Pending.tsx
  src/app/(userpage)/_components/SalesHistory/SalesHistory.tsx
  src/app/(userpage)/_components/SalesHistory/index.tsx
  src/app/(userpage)/_components/Tab/Tab.variants.ts
  src/app/(userpage)/_components/Tab/index.tsx
  src/app/(userpage)/_components/Transaction/Transaction.tsx
  src/app/(userpage)/_components/Transaction/TransactionItem.tsx
  src/app/(userpage)/_components/TransactionList/index.tsx
  src/app/(userpage)/_components/TransactionStatus/StatusCard.tsx
  src/app/(userpage)/_components/TransactionStatus/index.tsx
  src/app/(userpage)/_hooks/queries/useMyInfo.ts
  src/app/(userpage)/_hooks/queries/usePurchaseList.ts
  src/app/(userpage)/_hooks/queries/usePurchaseStatusList.ts
  src/app/(userpage)/_hooks/queries/useReviewList.ts
  src/app/(userpage)/_hooks/queries/useSaleList.ts
  src/app/(userpage)/_hooks/queries/useSaleStatusList.ts
  src/app/(userpage)/_hooks/queries/useUserInfo.ts
  src/app/(userpage)/_utils/calculateCounts.ts
  src/app/(userpage)/my/[slug]/page.tsx
  src/app/(userpage)/my/_components/Layout/index.tsx
  src/app/(userpage)/my/_components/MyInfo.tsx
  src/app/(userpage)/my/page.tsx
  src/app/(userpage)/user/[...slug]/page.tsx
  src/app/(userpage)/user/_components/Layout/index.tsx
  src/app/(userpage)/user/_components/UserInfo.tsx
  src/utils/types/user/users.ts
  tailwind.config.ts
Labels: ✨Feature

#207 refactor: 경매 상세페이지 댓글 API 연동 및 버그 수정, 모달 추가 수정
  public/assets/icon-sprite.svg
  src/app/_api/bookmark.ts
  src/app/_component/common/AuctionDetailFooterBar/index.tsx
  src/app/_component/common/AuctionDetailInfo/DefaultCase.tsx
  src/app/_component/common/AuctionDetailInfo/index.tsx
  src/app/_component/common/Bookmark/index.tsx
  src/app/_component/common/ChatMessage/index.tsx
  src/app/_component/common/LineChart/index.tsx
  src/app/_component/common/Modal/ModalType.variants.ts
  src/app/_component/common/Modal/index.tsx
  src/app/_component/common/TopThreeRank/index.tsx
  src/app/_hooks/queries/useGetBookmarkList.ts
  src/app/_hooks/queries/useSession.ts
  src/app/auctions/[auctionId]/Loading.tsx
  src/app/auctions/[auctionId]/_api/createComment.ts
  src/app/auctions/[auctionId]/_api/getCommentList.ts
  src/app/auctions/[auctionId]/_api/getComments.ts
  src/app/auctions/[auctionId]/_component/Comment/CommentInput.tsx
  src/app/auctions/[auctionId]/_component/Comment/index.tsx
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
  src/app/auctions/[auctionId]/_hooks/queries/useGetCheckBookmark.ts
  src/app/auctions/[auctionId]/_hooks/queries/useGetCommentList.ts
  src/app/auctions/[auctionId]/layout.tsx
  src/app/auctions/[auctionId]/page.tsx
  src/app/auctions/[auctionId]/successful-bid/page.tsx
  src/app/chatrooms/[chatRoomId]/_component/ChatRoomContent.tsx
  src/utils/function/authCheck.ts
  src/utils/types/comment/commentData.ts
  src/utils/types/search/search.ts
Labels: ✨Feature, 🐞BugFix, 🔨Refactor, 🔥빠른승인요청

#208 feat: 알림 목록 무한 스크롤 적용 및 미확인 알림 배지 구현
  public/assets/icon-sprite.svg
  src/app/(navigation)/home/_component/MainContentSection/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/notification/_api/notification.ts
  src/app/_component/notification/_component/AuctionNotification.tsx
  src/app/_component/notification/_component/NotificationItem.tsx
  src/app/_component/notification/_component/NotificationList.tsx
  src/app/_component/notification/_hooks/queries/useNotificationList.ts
  src/app/_component/notification/index.tsx
  src/utils/mocks/api/data/notificationData.ts
  src/utils/types/notification/index.ts
Labels: ✨Feature

#211 refactor: 리뷰 관련 API 명세에 맞춰 수정 및 버그 수정
  src/app/(userpage)/_api/mypage.ts
  src/app/(userpage)/_components/AllReviews/index.tsx
  src/app/(userpage)/_components/Info/index.tsx
  src/app/(userpage)/_components/ReviewItem/index.tsx
  src/app/(userpage)/_hooks/queries/useMyInfo.ts
  src/app/(userpage)/_hooks/queries/useReviewList.ts
  src/app/(userpage)/_hooks/queries/useUserInfo.ts
  src/utils/mocks/api/data/mypageData.ts
  src/utils/types/user/mypage.ts
Labels: 🔨Refactor, 🔥빠른승인요청

#203 design : 온보딩 페이지, 인기 검색어 검색 UI 개선 및 로딩 UI 추가
  public/mockServiceWorker.js
  src/app/_component/common/Loading/index.tsx
  src/app/_component/common/ProgressBar/ProgressBar.variants.ts
  src/app/_component/common/Skeleton/index.tsx
  src/app/_hooks/mutations/useImageUpload.ts
  src/app/onboarding/_component/SignupHeader.tsx
  src/app/onboarding/_component/funnel/FinishFunnel/_component/OnBoardingFail.tsx
  src/app/onboarding/_component/funnel/FinishFunnel/_component/OnBoardingSuccess.tsx
  src/app/onboarding/_component/funnel/FinishFunnel/index.tsx
  src/app/onboarding/_component/funnel/UserProfileSetting.tsx
  src/app/search/_component/RealTimePopular.tsx
  src/app/search/_component/RealTimePopularLoading.tsx
  src/app/signup/_hooks/mutations/useSignup.ts
Labels: 🎨Html&css

#218 fix: css깨지는 문제 해결
  src/app/auctions/[auctionId]/review/complete/page.tsx
Labels: 🐞BugFix, 🔥빠른승인요청

#213 refactor: 구매, 판매 내역 API 명세에 맞춰 수정 및 버그 수정
  src/app/(userpage)/_api/mypage.ts
  src/app/(userpage)/_components/EmptyList/index.tsx
  src/app/(userpage)/_components/Info/index.tsx
  src/app/(userpage)/_components/PurchaseHistory/index.tsx
  src/app/(userpage)/_components/SalesHistory/Bidding.tsx
  src/app/(userpage)/_components/SalesHistory/Finished.tsx
  src/app/(userpage)/_components/SalesHistory/Pending.tsx
  src/app/(userpage)/_components/SalesHistory/SalesHistory.tsx
  src/app/(userpage)/_components/Tab/index.tsx
  src/app/(userpage)/_components/Transaction/Transaction.tsx
  src/app/(userpage)/_components/Transaction/TransactionItem.tsx
  src/app/(userpage)/_components/TransactionList/index.tsx
  src/app/(userpage)/_components/TransactionStatus/index.tsx
  src/app/(userpage)/_hooks/queries/useMyInfo.ts
  src/app/(userpage)/_hooks/queries/usePurchaseList.ts
  src/app/(userpage)/_hooks/queries/usePurchaseStatusList.ts
  src/app/(userpage)/_hooks/queries/useSaleList.ts
  src/app/(userpage)/_hooks/queries/useSaleStatusList.ts
  src/app/(userpage)/_hooks/queries/useUserInfo.ts
  src/app/(userpage)/_utils/calculateCounts.ts
  src/app/(userpage)/my/[slug]/page.tsx
  src/app/(userpage)/my/_components/MyInfo/index.tsx
  src/app/(userpage)/my/page.tsx
  src/app/(userpage)/user/[...slug]/page.tsx
  src/app/(userpage)/user/[id]/[page]/page.tsx
  src/app/(userpage)/user/[id]/page.tsx
  src/app/(userpage)/user/_components/UserInfo/index.tsx
  src/app/_component/common/ProductCard/index.tsx
  src/utils/mocks/api/data/mypageData.ts
  src/utils/mocks/api/mypageApis.ts
  src/utils/types/user/mypage.ts
Labels: 🔨Refactor

#216 refactor: 메인 페이지, 경매 상세 페이지, 입찰 페이지 리팩토링
  public/assets/animations/Bids.lottie
  public/assets/icon-sprite.svg
  src/app/(navigation)/home/_component/AuctionFeedList/DefaultCard.tsx
  src/app/(navigation)/home/_component/DetailAuctionFeed/index.tsx
  src/app/(navigation)/home/_component/MainContentSection/AuctionListSection.tsx
  src/app/(navigation)/home/_hooks/queries/useRecommendAuction.ts
  src/app/(navigation)/home/loading.tsx
  src/app/_api/bookmark.ts
  src/app/_api/user.ts
  src/app/_component/common/AuctionBidsSection/index.tsx
  src/app/_component/common/BidsSuccessAnimation/index.tsx
  src/app/_component/common/Bookmark/index.tsx
  src/app/_component/common/ChatMessage/index.tsx
  src/app/_component/common/SlideCarousel/useDragScroll.ts
  src/app/_component/common/Spinner/index.tsx
  src/app/_hooks/mutations/useBookmark.ts
  src/app/_hooks/queries/useGetBookmarkList.ts
  src/app/_hooks/queries/useSession.ts
  src/app/auctions/[auctionId]/Loading.tsx
  src/app/auctions/[auctionId]/_api/getBids.ts
  src/app/auctions/[auctionId]/_component/AuctionBidsSection/index.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailFooterBar/index.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailInfo/DefaultCase.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailInfo/DefaultComponent.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailInfo/index.tsx
  src/app/auctions/[auctionId]/_component/CarouselDetailImage/index.tsx
  src/app/auctions/[auctionId]/_component/Comment/CommentInput.tsx
  src/app/auctions/[auctionId]/_component/Comment/index.tsx
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
  src/app/auctions/[auctionId]/_component/LineChart/index.tsx
  src/app/auctions/[auctionId]/_component/TopThreeRank/index.tsx
  src/app/auctions/[auctionId]/bidderList/_api/getChatRoomInfo.ts
  src/app/auctions/[auctionId]/loading.tsx
  src/app/auctions/[auctionId]/page.tsx
  src/app/auctions/[auctionId]/purchase/_api/postBid.ts
  src/app/auctions/[auctionId]/purchase/_component/AuctionBanner.tsx
  src/app/auctions/[auctionId]/purchase/_component/AuctionRanking.tsx
  src/app/auctions/[auctionId]/purchase/_hooks/useBidPost.ts
  src/app/auctions/[auctionId]/purchase/_hooks/useGetBidsInfo.ts
  src/app/auctions/[auctionId]/purchase/_hooks/useGetTopThreeRank.ts
  src/app/auctions/[auctionId]/purchase/loading.tsx
  src/app/auctions/[auctionId]/purchase/page.tsx
  src/app/auctions/[auctionId]/review/_hooks/useGetAuctionInfo.ts
  src/app/auctions/[auctionId]/review/page.tsx
  src/app/globals.css
  src/utils/function/authCheck.ts
  src/utils/types/auction/auctionDetail.ts
  src/utils/types/comment/commentData.ts
Labels: ✨Feature, 🔨Refactor

#221 fix : 검색결과 페이지 오류 수정 및 검색 결과 없을때 페이지 추가
  public/assets/animations/NoSearch.lottie
  src/app/search/[searchString]/_component/NotResult.tsx
  src/app/search/[searchString]/_component/NotSearchResult.tsx
  src/app/search/[searchString]/page.tsx
  src/app/search/_api/getSearchResults.tsx
Labels: ✨Feature, 🐞BugFix

#224 fix: 상품 등록 페이지 디자인 수정 및 API 연동 수정
  src/app/auctions/new/_api/registerAuction.ts
  src/app/auctions/new/_component/AuctionInfo/index.tsx
  src/app/auctions/new/_component/ProductInfo/ImageUploader/ImagePreviewer.tsx
  src/app/auctions/new/_utils/constants.ts
  src/app/auctions/new/layout.tsx
  src/app/chatrooms/_component/ChatRoomList.tsx
Labels: 🐞BugFix

#226 fix: Modal 버그 및 알림 에러 해결
  src/app/_component/common/Modal/ModalType.variants.ts
  src/app/_component/common/Modal/index.tsx
  src/app/_component/notification/_api/notification.ts
  src/app/_component/notification/_component/NotificationList.tsx
  src/app/_component/notification/_hooks/queries/useNotificationList.ts
  src/app/_component/notification/index.tsx
Labels: 🐞BugFix

#229 refactor : 프로젝트내 토큰이 필요한 Api 통신들에 fetchWithTokenRenewal 함수 적용
  src/app/(navigation)/home/_api/getAuctionRecommends.ts
  src/app/(userpage)/_api/mypage.ts
  src/app/_api/bookmark.ts
  src/app/_api/user.ts
  src/app/_component/notification/_api/notification.ts
  src/app/auctions/[auctionId]/_api/createComment.ts
  src/app/auctions/[auctionId]/bidderList/_api/createChatRoom.ts
  src/app/auctions/[auctionId]/bidderList/_api/getChatRoomInfo.ts
  src/app/auctions/[auctionId]/bidderList/_api/patchCancelBidder.ts
  src/app/auctions/[auctionId]/bidderList/_api/patchCompleteTransaction.ts
  src/app/auctions/[auctionId]/purchase/_api/postBid.ts
  src/app/auctions/[auctionId]/review/_api/createReview.ts
  src/app/auctions/new/_api/registerAuction.ts
  src/app/chatrooms/[chatRoomId]/_api/getChatContent.ts
  src/app/chatrooms/[chatRoomId]/_api/getchatRoomInfo.ts
  src/app/chatrooms/_api/getChatRooms.ts
  src/app/search/_api/getSearchResults.tsx
  src/utils/function/authCheck.ts
  src/utils/function/cookie.ts
  src/utils/function/fetchWithTokenRenewal.ts
Labels: 🔨Refactor

#230 fix: 빌드 오류 수정 및 로직 점검
  public/assets/icon-sprite.svg
  src/app/(userpage)/_components/TransactionList/index.tsx
  src/app/(userpage)/layout.tsx
  src/app/(userpage)/my/_components/Layout/index.tsx
  src/app/(userpage)/user/_components/Layout/index.tsx
  src/app/(userpage)/user/_components/UserInfo/index.tsx
  src/app/_component/common/Carousel/index.tsx
  src/app/_component/common/ChatMessage/index.tsx
  src/app/_component/common/Icon/type.ts
  src/app/_component/common/Navigation/index.tsx
  src/app/_hooks/queries/useAuth.ts
  src/app/_hooks/useVisibilityScroll.ts
  src/app/auctions/[auctionId]/_component/Comment/index.tsx
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
  src/app/auctions/new/_hooks/mutations/useReigsterAuction.ts
  src/app/auctions/new/page.tsx
  src/app/bookmark/layout.tsx
  src/app/bookmark/page.tsx
  src/app/chatrooms/[chatRoomId]/_component/ChatRoomContent.tsx
  src/app/chatrooms/page.tsx
  src/app/onboarding/page.tsx
  src/app/signin/_hooks/mutations/useSignin.ts
  src/utils/mocks/api/authApis.ts
  src/utils/mocks/api/bids.ts
  src/utils/mocks/api/data/authData.ts
  src/utils/mocks/api/data/bidData.ts
  src/utils/mocks/api/data/popularSearchData.ts
  src/utils/mocks/api/data/postListData.ts
  src/utils/mocks/api/data/token.ts
  src/utils/mocks/api/data/userData.ts
  src/utils/mocks/browser.ts
  src/utils/mocks/handlers.ts
Labels: 🐞BugFix, 🔨Refactor

#231 feat: 미들웨어 추가 및 getUserInfo 함수 수정
  src/app/_api/user.ts
  src/middleware.ts
Labels: ✨Feature, 🔨Refactor

#233 fix: type 에러 수정
  src/app/auctions/[auctionId]/_component/DetailInfoSection.tsx
Labels: 🐞BugFix

#244 fix: middleware 수정
  src/middleware.ts
Labels: 🐞BugFix

#245 fix: 네비게이션 스크롤 이벤트 기능 제거
  src/app/(userpage)/layout.tsx
  src/app/_component/common/Navigation/index.tsx
  src/app/_hooks/useVisibilityScroll.ts
  src/app/bookmark/layout.tsx
Labels: 🐞BugFix

#248 feat : 로그인 페이지 디자인 변경
  public/assets/images/hans/hans.webp
  public/assets/images/hans/hansHands.webp
  src/app/globals.css
  src/app/signin/_component/EmailLoginForm.tsx
  src/app/signin/_component/Hans.tsx
  src/app/signin/page.tsx
  tailwind.config.ts
Labels: 🎨Html&css

#251 fix: bidderList 버그 수정
  src/app/auctions/[auctionId]/bidderList/_hooks/useGetChatRoomInfo.ts
  src/app/auctions/[auctionId]/bidderList/_hooks/usePatchTransactionCancel.ts
  src/app/auctions/[auctionId]/bidderList/page.tsx
Labels: 🐞BugFix

#256 fix : 검색결과 페이지 bookmarkCount 제대로 표기 안되는 버그 수정
  src/app/search/[searchString]/page.tsx
Labels: 🐞BugFix

#261 refactor: 입찰, 경매 상세 페이지 css 수정 및 상품등록 에러 문제 처리
  src/app/(navigation)/layout.tsx
  src/app/auctions/[auctionId]/_component/AuctionDetailFooterBar/index.tsx
  src/app/auctions/[auctionId]/purchase/page.tsx
  src/app/auctions/new/_component/AuctionInfo/index.tsx
  src/app/auctions/new/_component/ProductInfo/index.tsx
  src/app/auctions/new/_component/SearchAddressBtn/index.tsx
  src/app/auctions/new/_utils/constants.ts
  src/app/globals.css
Labels: 🐞BugFix, 🎨Html&css

#263 fix: 로그인 시 알림설정 팝업 뜨도록 변경
  src/app/(navigation)/home/_api/getAuctionRecommends.ts
  src/app/_api/bookmark.ts
  src/app/_api/user.ts
  src/app/auctions/[auctionId]/_api/createComment.ts
  src/app/signin/_hooks/mutations/redirectActionsHome.ts
  src/app/signin/_hooks/mutations/useSignin.ts
Labels: 🐞BugFix

#265 fix: 기능 테스트 후 버그 수정
  src/app/(userpage)/_components/Info/index.tsx
  src/app/_component/common/InputPrice/index.tsx
  src/app/_component/notification/_hooks/queries/useNotificationBadge.ts
  src/app/_component/notification/_hooks/queries/useNotificationList.ts
  src/app/auctions/new/_component/AuctionInfo/index.tsx
  src/app/auctions/new/page.tsx
  src/utils/mocks/api/data/mypageData.ts
  src/utils/types/user/mypage.ts
Labels: 🐞BugFix

#268 fix : 검색 필터 다크모드 적용 안됐을 때 디자인 이상해지는 버그 수정
  src/app/search/[searchString]/_component/SearchFilter.tsx
  src/app/search/[searchString]/layout.tsx
Labels: 🐞BugFix

#271 feat: 거래 후기 완료 모달 실제 데이터 연동
  src/app/auctions/[auctionId]/review/ReviewReceipt/_utils/formatDate.ts
  src/app/auctions/[auctionId]/review/ReviewReceipt/index.tsx
  src/app/auctions/[auctionId]/review/_api/createReview.ts
  src/app/auctions/[auctionId]/review/_hooks/useProduct.ts
  src/app/auctions/[auctionId]/review/page.tsx
  src/utils/types/auction/auctionReivewEnroll.ts
Labels: ✨Feature

#273 fix : 검색 필터 중 거래방식 적용 오류 수정 및 검색 결과 카드 디자인 요소 수정
  src/app/search/[searchString]/_component/SearchFilter.tsx
  src/app/search/[searchString]/page.tsx
Labels: ✨Feature
